# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ka1eid's SandBox
subtitle: '千仞高塔，筑基于此'
description: ''
keywords:
author: Kaleid Scoper
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://kaleidscoper.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# 主题加载忽略列表
skip_render:
  - resume/**
  - resume-en/**
  - 404.html
  - mc-server/**


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
# 声明！！！本站用分类来归档文章，标签仅用于检索文章
default_category: uncategorized
category_map:
  技术: tech # 一级分类，下辖两个二级分类安全和开发

  安全: sec # 二级分类
  开源情报: osint
  Web安全: websec
  逆向工程: reverse
  二进制安全: pwn
  密码学: crypto
  杂项: misc

  开发: dev # 二级分类
  Web开发: webdev
  UE5开发: ue5
  安卓开发: android
  桌面开发: desktop

  游戏: game # 一级分类
  我的世界: minecraft
  三国杀: sanguosha
  王者荣耀: kog
  其他游戏: miscgame

  日记: diary # 一级分类，文章的文件名也直接采用diary-年份
  2010年: diary-2010
  2011年: diary-2011
  2012年: diary-2012
  2013年: diary-2013
  2014年: diary-2014
  2015年: diary-2015
  2016年: diary-2016
  2017年: diary-2017
  2018年: diary-2018
  2019年: diary-2019
  2020年: diary-2020
  2021年: diary-2021
  2022年: diary-2022
  2023年: diary-2023
  2024年: diary-2024
  2025年: diary-2025

  杂谈: talk # 一级分类

  旅行: travel # 二级分类，文章的文件名直接采用城市英文名
  国内: domestic
  国外: abroad

  电影剧集: movie
  漫画动漫: otaku
  音乐品鉴: music
  书刊诗文: book
  人文社科: humanity # 下辖历史、哲学、政治等分类，但此二级分类处不再细分，使用tag

  未分类: uncategorized # 一级分类

tag_map:
  教程: tutorial
  博客: blog
  转载: repost
  原创: original
  翻译: translation

  Git: git
  Markdown: markdown
  LaTeX: latex
  Linux: linux

  Hexo: hexo
  WordPress: wordpress
  HTML: html
  CSS: css
  JavaScript: js
  Vue: vue
  PHP: php
  数据库: SQL

  C++: cpp
  C: c
  C#: csharp
  Python: python
  Java: java

  建筑学: architecture
  哲学: philosophy
  历史: history
  文学: literature
  语言学: linguistics
  美学: aesthetics
  经济学: economics
  政治学: politics
  法学: law
  教育学: education
  心理学: psychology
  社会学: sociology
  人类学: anthropology
  地理学: geography
  生物学: biology
  化学: chemistry
  物理学: physics
  数学: mathematics
  计算机科学: computer science
  医学: medicine
  管理学: management
  统计学: statistics


# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ayer

# Markdown-it configuration
markdown_it:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '""'''
  plugins:
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-container
    - markdown-it-deflist
    - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-sub
    - markdown-it-sup

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
